### ISSUE TITLE
Extension freezes inkscape 

### ISSUE THREAD

**Issue by ollylove** [tzunghaor/inkscape-eps-export#1]
Hi, I'm trying to export an inkscape design as .eps using your extension, but no message appears, inkscape freezes and nothing is saved nor exported.. am I doing something wrong??.. thank you!!

**Comment by tzunghaor** [comment]
Sorry, I thought I'll get mail when somebody opens an issue, so I did not check this page in a while.
Anyway, if the problem still exists, could you upload the SVG that you tried to save?
