### ISSUE TITLE
non-Inkscape SVGs

### ISSUE THREAD

**Issue by hskoken** [tzunghaor/inkscape-eps-export#11]
I am creating SVG files via fabrics.js. As you said there is not any id. Thank you for your response.

**Comment by tzunghaor** [comment]
Please upload some example files - maybe there are other features in your SVG format that my script doesn't expect.

**Comment by hskoken** [comment]
I attached 3 sample svg files.

Thank you.


[samples.zip](https://github.com/tzunghaor/inkscape-eps-export/files/5251280/samples.zip)

**Comment by tzunghaor** [comment]
I will have time next week to work on this.

**Comment by tzunghaor** [comment]
I committed some changes and created a new release (1.0.7) that doesn't crash when converting your files.
But your files use (semi-)transparency - EPS cannot handle it, so the output will not look as nice as your SVG files.

**Comment by erstesoftware** [comment]
But it worked for non-transparent images. Thank you very much.

**Comment by hskoken** [comment]
But it worked for non-transparent images. Thank you very much.
