### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by kholil997** [tzunghaor/inkscape-eps-export#12]
salam
can you help me,, hehe

i use windows 10 64-bit.. inkscape 1.0.1 and inkscape 9.2

in file there bitmap (just brain)

i'm indonesian

Traceback (most recent call last):
File “aieps_output.py”, line 1169, in
print(converter.convert())
File “aieps_output.py”, line 1141, in convert
self.walkElem(self.root)
File “aieps_output.py”, line 882, in walkElem
self.walkElem(child)
File “aieps_output.py”, line 882, in walkElem
self.walkElem(child)
File “aieps_output.py”, line 882, in walkElem
self.walkElem(child)
File “aieps_output.py”, line 865, in walkElem
self.elemStop(elem)
File “aieps_output.py”, line 705, in elemStop
offset = float(elem.get(‘offset’)) * 100
ValueError: could not convert string to float: ‘0%’

[handtag STIFIn.zip](https://github.com/tzunghaor/inkscape-eps-export/files/5619577/handtag.STIFIn.zip)

**Comment by tzunghaor** [comment]
I fixed the above issue for your file in release 1.0.8
But be aware, your picture contains:
* an embedded image, which is not supported by my script
* half-transparent elements - transparency is generally not supported by EPS format

**Comment by kholil997** [comment]
ok, thank you very much,, its work
