### ISSUE TITLE
File "aieps_output.py", line 1103     print "missing filename"

### ISSUE THREAD

**Issue by fdanangp** [tzunghaor/inkscape-eps-export#4]
It show warning and **ALL of my inkscape works can't be saved** using this extension. i run inkscape 0.92.4 on clear linux os. 

File "aieps_output.py", line 1103
    print "missing filename"
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("missing filename")?

this is the screenshots
![Screenshot from 2019-09-19 21-49-42](https://user-images.githubusercontent.com/10324059/65255432-17718080-db28-11e9-8702-2923089b0f44.png)
![Screenshot from 2019-09-19 21-50-18](https://user-images.githubusercontent.com/10324059/65255443-1b9d9e00-db28-11e9-801b-8e4516cebd67.png)

**Comment by tzunghaor** [comment]
Your default python version is probably 3. I've made the script compatible with this python version in v1.0.4 - try that out, and please let me know if it fixed the issue.

Anyway, if you have problem running other scripts, you can set which python interpreter you want to use with inkscape as described [here](http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29)

**Comment by hskoken** [comment]
Thank you for this wondeful extension. I made it work at commandline and get this error:
Traceback (most recent call last):
  File "aieps_output.py", line 1137, in <module>
    print(converter.convert())
  File "aieps_output.py", line 1109, in convert
    self.walkElem(self.root)
  File "aieps_output.py", line 850, in walkElem
    self.walkElem(child)
  File "aieps_output.py", line 850, in walkElem
    self.walkElem(child)
  File "aieps_output.py", line 821, in walkElem
    self.elemRect(elem)
  File "aieps_output.py", line 575, in elemRect
    self.elemPath(elem, pathData)
  File "aieps_output.py", line 319, in elemPath
    self.epspath += '\n%AI3_Note: ' + elem.get('id') + '\n'
TypeError: can only concatenate str (not "NoneType") to str

I am new at python. So it would be great if you have a sloution.

**Comment by tzunghaor** [comment]
@hskoken  next time please open a new issue if your comment doesn't relate to any existing issue.

Your TypeError suggests that some `<path>` elements in your SVG don't have id attribute - I think you didn't create the file with Inkscape. I've written the script for Inkscape and it assigns an id to every `<path>` - if you open your file with Inkscape and export to EPS, then it should probably work.

If you wish to have more support for non-Inkscape SVGs, then please open a new issue with some SVG files. (Though I cannot promise that I will work on it anytime soon.)
